In [1]:
print(1)

1


#### NumPy

Descarga:

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\andre\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Llamar al paquete:

In [5]:
import numpy as np

Crear arreglo en numpy

In [6]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


Arreglo "multidimensional":

In [8]:
arr = np.array (([1,2,3], [4,5,6]))
print (arr)

[[1 2 3]
 [4 5 6]]


ndim: número de dimensiones del arreglo, se puede visualizar con "arr[0]"

In [10]:
arr = np.array ([1,2,3,4,5,6], ndmin=3)
print(arr.ndim)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


Arreglos personalizados <br>
Arreglo 2x2 de puros 0s:

In [11]:
arr=np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


Arreglo 3x3 de puros 1s:

In [12]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Arreglo 3x3 con valores aleatorios entre el 1 y 0:

In [13]:
arr= np.random.rand(3,3)
print(arr)

[[0.67760846 0.18253136 0.79154469]
 [0.55862526 0.83643592 0.12509247]
 [0.51923163 0.71059793 0.29738968]]


##### Operaciones de arreglos

Suma:

In [15]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1, arr2)
print(arr3)

[5 7 9]


Resta:

In [17]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.subtract(arr1, arr2)
print(arr3)

[-3 -3 -3]


Otros comandos: <br>
np.multiply <br>
np.divide

#### Agregación

In [19]:
#media:
arr= [1,5,7]
media= np.mean(arr)
print(media)

4.333333333333333


In [ ]:
#mediana:
arr= [1,5,7]
mediana = np.median(arr)
print(mediana)

Otros comandos: <br>
Valor máximo np.max <br>
Valor mínimo np.min

#### Indexación

In [20]:
arr = np.array([1,2,3,4,5,6])
print(arr[0]) #primer valor de la lista

1


In [21]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1]) #ultimo valor de la lista

6


In [24]:
arr = np.array(([1,2,3], [4,5,6]))
print(arr[1, 2]) #coordenadas, del arreglo 1, manda el valor 2

6


Recuerda que python cuenta a partir del 0

#### Slicing

Imprimir por rangos:

In [26]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [27]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4:2]) #De los valores 1 al 4, de dos en dos

[2 4]


In [28]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2]) #De toda la lista, de dos en dos

[1 3 5]


#### Tipos de datos

In [1]:
import numpy as np
arr = np.array(["b", "a"])
print(arr.dtype)

<U1


El resultado impreso no es numérico (dtype)

In [2]:
arr = np.array([1.1, 2.5])
print(arr.dtype)

float64


Resultado tipo float

Definir tipo:

In [6]:
arr = np.array([1,2,3], dtype='S')
print(arr.dtype)


|S1


dtypes: <br>
i interger <br>
b booleano <br>
f flotante <br>
S string <br>


Copy vs New

In [9]:
arr = np.array([1, 2, 3])
x=arr.copy()
y=arr.view()

print(arr)
print(x)
print(y)

[1 2 3]
[1 2 3]
[1 2 3]


View es en tiempo real mientras que copy es lo que estaba cuando generaste el comando.

Concatenar

In [10]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
arr3= np.concatenate([arr1, arr2])
print(arr3)

[1 2 3 4 5 6]


Búsqueda <br>
Te devuelve el lugar (índice del arreglo)

In [12]:
arr= np.array([1,2, 2, 4, 5, 5, 4])
x = np.where(arr == 5)
print(x)

(array([4, 5], dtype=int64),)


Te dice el lugar y tipo de dato

Ordenar:

In [13]:
arr= np.array ([2, 5, 6, 4, 3 , 8, 1])
x= np.sort(arr)
print(x)

[1 2 3 4 5 6 8]
